//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace BikeShop.BicycleChallenge
{
    
    
    /// <summary>
    /// The default implementation of the Component class
    /// </summary>
    [XmlNamespaceAttribute("http://www.fzi.de/MULTI/2017/bicycleChallenge")]
    [XmlNamespacePrefixAttribute("bikes")]
    [ModelRepresentationClassAttribute("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Component")]
    public abstract partial class Component : Part, BikeShop.BicycleChallenge.IComponent, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Weight property
        /// </summary>
        private double _weight;
        
        private static Lazy<ITypedElement> _weightAttribute = new Lazy<ITypedElement>(RetrieveWeightAttribute);
        
        private static Lazy<ITypedElement> _partsReference = new Lazy<ITypedElement>(RetrievePartsReference);
        
        /// <summary>
        /// The backing field for the Parts property
        /// </summary>
        private ObservableCompositionList<IPart> _parts;
        
        private static IClass _classInstance;
        
        public Component()
        {
            this._parts = new ObservableCompositionList<IPart>(this);
            this._parts.CollectionChanging += this.PartsCollectionChanging;
            this._parts.CollectionChanged += this.PartsCollectionChanged;
        }
        
        /// <summary>
        /// The Weight property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public double Weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                if ((this._weight != value))
                {
                    double old = this._weight;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnWeightChanging(e);
                    this.OnPropertyChanging("Weight", e, _weightAttribute);
                    this._weight = value;
                    this.OnWeightChanged(e);
                    this.OnPropertyChanged("Weight", e, _weightAttribute);
                }
            }
        }
        
        /// <summary>
        /// The Parts property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public ICollectionExpression<IPart> Parts
        {
            get
            {
                return this._parts;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ComponentChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new ComponentReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Component")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Weight property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> WeightChanging;
        
        /// <summary>
        /// Gets fired when the Weight property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> WeightChanged;
        
        private static ITypedElement RetrieveWeightAttribute()
        {
            return ((ITypedElement)(((ModelElement)(BikeShop.BicycleChallenge.Component.ClassInstance)).Resolve("Weight")));
        }
        
        /// <summary>
        /// Raises the WeightChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWeightChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.WeightChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the WeightChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWeightChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.WeightChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrievePartsReference()
        {
            return ((ITypedElement)(((ModelElement)(BikeShop.BicycleChallenge.Component.ClassInstance)).Resolve("Parts")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Parts property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void PartsCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("Parts", e, _partsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Parts property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void PartsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Parts", e, _partsReference);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "WEIGHT"))
            {
                return this.Weight;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "PARTS"))
            {
                return this._parts;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "WEIGHT"))
            {
                this.Weight = ((double)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._parts))
            {
                return "Parts";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Component")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Component class
        /// </summary>
        public class ComponentChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Component _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ComponentChildrenCollection(Component parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Parts.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Parts.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Parts.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IPart partsCasted = item.As<IPart>();
                if ((partsCasted != null))
                {
                    this._parent.Parts.Add(partsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Parts.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Parts.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> partsEnumerator = this._parent.Parts.GetEnumerator();
                try
                {
                    for (
                    ; partsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = partsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    partsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IPart partItem = item.As<IPart>();
                if (((partItem != null) 
                            && this._parent.Parts.Remove(partItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Parts).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Component class
        /// </summary>
        public class ComponentReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Component _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ComponentReferencedElementsCollection(Component parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Parts.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Parts.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Parts.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IPart partsCasted = item.As<IPart>();
                if ((partsCasted != null))
                {
                    this._parent.Parts.Add(partsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Parts.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Parts.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> partsEnumerator = this._parent.Parts.GetEnumerator();
                try
                {
                    for (
                    ; partsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = partsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    partsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IPart partItem = item.As<IPart>();
                if (((partItem != null) 
                            && this._parent.Parts.Remove(partItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Parts).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Weight property
        /// </summary>
        private sealed class WeightProxy : ModelPropertyChange<BikeShop.BicycleChallenge.IComponent, double>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public WeightProxy(BikeShop.BicycleChallenge.IComponent modelElement) : 
                    base(modelElement, "Weight")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override double Value
            {
                get
                {
                    return this.ModelElement.Weight;
                }
                set
                {
                    this.ModelElement.Weight = value;
                }
            }
        }
    }
}

