//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace BikeShop.BicycleChallenge
{
    
    
    /// <summary>
    /// The default implementation of the Fork class
    /// </summary>
    [XmlNamespaceAttribute("http://www.fzi.de/MULTI/2017/bicycleChallenge")]
    [XmlNamespacePrefixAttribute("bikes")]
    [ModelRepresentationClassAttribute("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Fork")]
    public partial class Fork : Component, IFork, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Color property
        /// </summary>
        private string _color;
        
        private static Lazy<ITypedElement> _colorAttribute = new Lazy<ITypedElement>(RetrieveColorAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The Color property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public string Color
        {
            get
            {
                return this._color;
            }
            set
            {
                if ((this._color != value))
                {
                    string old = this._color;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnColorChanging(e);
                    this.OnPropertyChanging("Color", e, _colorAttribute);
                    this._color = value;
                    this.OnColorChanged(e);
                    this.OnPropertyChanged("Color", e, _colorAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Fork")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Color property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ColorChanging;
        
        /// <summary>
        /// Gets fired when the Color property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ColorChanged;
        
        private static ITypedElement RetrieveColorAttribute()
        {
            return ((ITypedElement)(((ModelElement)(BikeShop.BicycleChallenge.Fork.ClassInstance)).Resolve("Color")));
        }
        
        /// <summary>
        /// Raises the ColorChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnColorChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ColorChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ColorChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnColorChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ColorChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "COLOR"))
            {
                return this.Color;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "COLOR"))
            {
                this.Color = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.fzi.de/MULTI/2017/bicycleChallenge#//Fork")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Color property
        /// </summary>
        private sealed class ColorProxy : ModelPropertyChange<IFork, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ColorProxy(IFork modelElement) : 
                    base(modelElement, "Color")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Color;
                }
                set
                {
                    this.ModelElement.Color = value;
                }
            }
        }
    }
}

