//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace BikeShop.BicycleChallenge
{
    
    
    /// <summary>
    /// The public interface for Frame
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Frame))]
    [XmlDefaultImplementationTypeAttribute(typeof(Frame))]
    public interface IFrame : IModelElement, BikeShop.BicycleChallenge.IComponent
    {
        
        /// <summary>
        /// The Color property
        /// </summary>
        string Color
        {
            get;
            set;
        }
        
        /// <summary>
        /// The SerialNumber property
        /// </summary>
        string SerialNumber
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Color property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ColorChanging;
        
        /// <summary>
        /// Gets fired when the Color property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ColorChanged;
        
        /// <summary>
        /// Gets fired before the SerialNumber property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SerialNumberChanging;
        
        /// <summary>
        /// Gets fired when the SerialNumber property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SerialNumberChanged;
    }
}

