//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace BikeShop.BicycleChallenge
{
    
    
    /// <summary>
    /// The public interface for MountainBike
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(MountainBike))]
    [XmlDefaultImplementationTypeAttribute(typeof(MountainBike))]
    public interface IMountainBike : IModelElement, IBicycle
    {
        
        /// <summary>
        /// The SuspensionFork property
        /// </summary>
        ISuspensionFork SuspensionFork
        {
            get;
            set;
        }
        
        /// <summary>
        /// The RearSuspension property
        /// </summary>
        IRearSuspension RearSuspension
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the SuspensionFork property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SuspensionForkChanging;
        
        /// <summary>
        /// Gets fired when the SuspensionFork property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SuspensionForkChanged;
        
        /// <summary>
        /// Gets fired before the RearSuspension property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RearSuspensionChanging;
        
        /// <summary>
        /// Gets fired when the RearSuspension property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RearSuspensionChanged;
    }
}

