//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace BikeShop.BicycleChallenge
{
    
    
    /// <summary>
    /// The public interface for RaceFrame
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(RaceFrame))]
    [XmlDefaultImplementationTypeAttribute(typeof(RaceFrame))]
    public interface IRaceFrame : IModelElement, IFrame
    {
        
        /// <summary>
        /// The TopTubeLength property
        /// </summary>
        double TopTubeLength
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DownTubeLength property
        /// </summary>
        double DownTubeLength
        {
            get;
            set;
        }
        
        /// <summary>
        /// The SeatTubeLength property
        /// </summary>
        double SeatTubeLength
        {
            get;
            set;
        }
        
        /// <summary>
        /// The Material property
        /// </summary>
        Material Material
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the TopTubeLength property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TopTubeLengthChanging;
        
        /// <summary>
        /// Gets fired when the TopTubeLength property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TopTubeLengthChanged;
        
        /// <summary>
        /// Gets fired before the DownTubeLength property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DownTubeLengthChanging;
        
        /// <summary>
        /// Gets fired when the DownTubeLength property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DownTubeLengthChanged;
        
        /// <summary>
        /// Gets fired before the SeatTubeLength property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SeatTubeLengthChanging;
        
        /// <summary>
        /// Gets fired when the SeatTubeLength property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SeatTubeLengthChanged;
        
        /// <summary>
        /// Gets fired before the Material property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MaterialChanging;
        
        /// <summary>
        /// Gets fired when the Material property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MaterialChanged;
    }
}

